### ISSUE TITLE
Pagination component still not ssr friendly

### ISSUE THREAD

**Issue by kliyer-ai** [ulivz/vuepress-plugin-blog#11]
I just updated the plugin to the latest version (1.2.3) and saw commit 3e03666b358928cd85ebbcf486cd034f0b6b8f33. However, when I import the component like so

`
import { Pagination } from '@vuepress/plugin-blog/lib/client/components'
`

I still get an error when building the application. Any idea why?

**Comment by ulivz** [comment]
Could you provide a minimal reproduction repo?

**Comment by kliyer-ai** [comment]
Sorry it was a mistake on my side. I deleted the folders node_modules and dist and now it works.
