### ISSUE TITLE
changelog wanted

### ISSUE THREAD

**Issue by Mister-Hope** [ulivz/vuepress-plugin-blog#27]
## Feature request

I wounder if the author can publish it on the release panel and make a changelog? Thanks

**Comment by newsbielt703** [comment]
Here is the [changelog](https://github.com/ulivz/vuepress-plugin-blog/blob/master/CHANGELOG.md). 
I'll handle the `github release` next weekend.

**Comment by newsbielt703** [comment]
[Releases](https://github.com/ulivz/vuepress-plugin-blog/releases)

**Comment by Mister-Hope** [comment]
Wow thanks :)
