### ISSUE TITLE
要放弃 @vuepress/plugin-blog 了吗

### ISSUE THREAD

**Issue by trafficmgr** [ulivz/vuepress-plugin-blog#3]
## Is the plugin deprecated ?

最近看到插件 `@vuepress/plugin-blog@next` 从仓库里移除了[10dfb66](/vuejs/vuepress/commit/10dfb6695dec7d9bbd2265f63ad50e008663b82c)，一时间不知所措。目前只能维持在 `1.0.0-alpha.49`

**Comment by ulivz** [comment]
可以在这里看到为什么我们我们会从主仓库将博客插件迁移出来：https://github.com/vuejs/vuepress/issues/36#issuecomment-498633025

旧的博客插件功能比较差，且在 frontmatter 分类下无法支持分页，新的博客插件拓展性更强，且 API 更简单，可以看看这个使用 70 行代码写的博客主题：https://github.com/ulivz?tab=repositories

**Comment by wensonsmith** [comment]
我用老版本的plugin-blog正在写主题。。主题还没写好，新版本都出来了，再适配一哈 [捂脸哭]

**Comment by recoluan** [comment]
我的主题完全按照原来的弄的，你这变得有点难受啊，一点都不向下兼容啊。

**Comment by recoluan** [comment]
> @vuepress/plugin-blog 并没有被放弃，只是迁移出来重写和单独维护了，包名维持不变。
> 
> 可以在这里看到为什么我们我们会从主仓库将博客插件迁移出来单独维护：[vuejs/vuepress#36 (comment)](https://github.com/vuejs/vuepress/issues/36#issuecomment-498633025)
> 
> 旧的博客插件功能比较差，且在 frontmatter 分类下无法支持分页，新的博客插件拓展性更强，且 API 更简单，可以看看这个使用 70 行代码写的博客主题：https://github.com/ulivz/70-lines-of-vuepress-blog-theme

建议添加上 `$categories` 全局变量，我觉得没必要限制住主题作者处理分类的方式，不然很影响主题制作者的发挥

**Comment by wensonsmith** [comment]
@recoluan 

$categories 没有去掉，我理解的是作者吧 tag 和 category 都抽象成一种东西了，就是在 `frontmatter` 里配置就行了。

**Comment by ulivz** [comment]
> 衷心建议添加上 $categories 全局变量，我觉得没必要限制住主题作者处理分类的方式，不然很影响主题制作者的发挥

没有去掉的，以前的全局变量都是写死的，但现在你可以随意地创造，举个例子：https://github.com/ulivz/blog/blob/master/src/.vuepress/config.js#L6

**Comment by recoluan** [comment]
> @recoluan
> 
> $categories 没有去掉，我理解的是作者吧 tag 和 category 都抽象成一种东西了，就是在 `frontmatter` 里配置就行了。

明白了，谢谢

**Comment by recoluan** [comment]
> > 衷心建议添加上 $categories 全局变量，我觉得没必要限制住主题作者处理分类的方式，不然很影响主题制作者的发挥
> 
> 没有去掉的，以前的全局变量都是写死的，但现在你可以随意地创造，举个例子：https://github.com/ulivz/blog/blob/master/src/.vuepress/config.js#L6
> 
> 建议好好看看新博客插件的文档~

好的，谢谢，文档里一直在拿 tag 举例子，开始没太看明白

**Comment by ulivz** [comment]
建议 issue 也用英文提，这样所有人都可以答复。
