### ISSUE TITLE
frontmatters' entry pages are not under its index path, but under /{id}/

### ISSUE THREAD

**Issue by GNQG** [ulivz/vuepress-plugin-blog#4]
config.js:
```javascript
module.exports = {
  plugins: [
    ['@vuepress/blog', {
      frontmatters: [
        {
          id: "id",
          keys: ['tag'],
          path: '/subdir/',
          // ...
        }
      ]
    ]
  ]
  // ...
}

```

expected `this.$site.pages`:
```javascript
[
  {
    "frontmatter": {"title": "some_tag | id"},
    "regularPath": "/subdir/some_tag/",
    "path": "/subdir/some_tag/",
    // ...
  },
  // ...
]
```

actual `this.$site.pages`:
```javascript
[
  {
    "frontmatter": {"title": "some_tag | id"},
    "regularPath": "/id/some_tag/",
    "path": "/id/some_tag/",
    // ...
  },
  // ...
]
```

**Comment by ulivz** [comment]
Do you read the doc?

What's the expected behavior and actual behavior?

**Comment by Enigmatrix** [comment]
Not the OP, but the doc/site in Github mentions nothing about the using the `id` as the mount path for tags. However, even if it were the intended behavior, I think it might be better to have the tag pages relative to the tag 'list' page refered to by `path`. I understand that you can simulate the behavior by setting the `id` and `path` to the same value, but if the `path` & `id` is a subdir like `/blog/tag`, then the title of the page will be `{tag} | /blog/tag`, which is uncomfortable to read.

**Comment by yuicer** [comment]
@Enigmatrix  this blog-plugin will not change the $site.pages .it mainly probvide the $pagination parma.  and you can see the docs here [https://github.com/ulivz/vuepress-plugin-blog/tree/master/docs/pagination](https://github.com/ulivz/vuepress-plugin-blog/tree/master/docs/pagination)

**Comment by ulivz** [comment]
See rendered docs: https://vuepress-plugin-blog.ulivz.com/pagination/
