### ISSUE TITLE
$pagination.pages的返回数组排序问题

### ISSUE THREAD

**Issue by eliot-ye** [ulivz/vuepress-plugin-blog#7]
对博客来说，文章的排序不一定是按时间正序排序的，有可能是按时间倒序排序，是不是应该有一个倒序排序的选项？

现在的插件在没有分页时，可以手动reverse()，但一旦分页，手动reverse()后的逻辑就不对了

**Comment by eliot-ye** [comment]
好像目录的排序有问题，能说明一下排序的逻辑吗

**Comment by ulivz** [comment]
1. 文章的排序是可以定制的，只是文档还没有写；
2. 目录的排序有问题，什么问题？

**Comment by eliot-ye** [comment]
https://gitee.com/xspiritx/blog/tree/dev/src/technology
https://xspiritx.gitee.io/blog/
对GitHub不是很熟，这是我现在的项目里的文章目录和build后的排序，不一致

**Comment by kliyer-ai** [comment]
How can I reverse the order of the pagination so that the most recent post shows up first? Thanks.

**Comment by kliyer-ai** [comment]
I saw the documentation was updated. I found it now. Thanks.

**Comment by ulivz** [comment]
See: [pagination > sorter](https://vuepress-plugin-blog.ulivz.com/pagination/#sorter)
