### ISSUE TITLE
How to add images folder

### ISSUE THREAD

**Issue by Assassyn** [ulivz/vuepress-plugin-blog#9]
I am trying to store the images for the blog post inside any folder, but it seems that I am not able to force vuepress to copy content of my cusotm one during build. 

I am also not able to find any documentation about where to store imnages.

**Comment by yuicer** [comment]
> I am trying to store the images for the blog post inside any folder, but it seems that I am not able to force vuepress to copy content of my cusotm one during build.
> 
> I am also not able to find any documentation about where to store imnages.

images folder can be stored `docs/.vuepress/public/img`  .vuepress/public/ 文件夹下
so we can handle it like the static assets.

related docs [https://v1.vuepress.vuejs.org/zh/guide/assets.html#%E5%9F%BA%E7%A1%80%E8%B7%AF%E5%BE%84](https://v1.vuepress.vuejs.org/zh/guide/assets.html#%E5%9F%BA%E7%A1%80%E8%B7%AF%E5%BE%84)

**Comment by Assassyn** [comment]
I am alsmost sure I have tried to add folder to .vuepress/public.
